const fs = require('fs');
const path = require('path');
const scrapedProducts = require('../src/lib/scraped-products.json');

const BRAIN_DIR = 'C:\\Users\\karee\\.gemini\\antigravity\\brain\\c0079beb-c806-4e9a-8e8b-4a5825000857';
const DEST_DIR = path.join(__dirname, '../public/images/categories');

if (!fs.existsSync(DEST_DIR)) fs.mkdirSync(DEST_DIR, { recursive: true });

// The 9 images successfully generated by AI
const aiImages = {
  'bearings': 'bearings_category_1774093574620.png',
  'linear': 'category_linear_1774093811711.png',
  'ball-screw': 'category_ball_screw_1774093824008.png',
  'hard-chrome': 'category_hard_chrome_1774093836978.png',
  'lead-screw': 'category_lead_screw_1774094004169.png',
  'fasteners': 'category_fasteners_1774094852951.png',
  'housings': 'category_housings_1774094870799.png',
  'pulleys': 'category_pulleys_1774094886870.png',
  'misc': 'category_misc_1774094902306.png'
};

// Top categories
const TOP_CATS = [
  "bearings", "linear", "ball-screw", "hard-chrome",
  "lead-screw", "fasteners", "housings", "pulleys", "misc"
];

let successCount = 0;

for (const cat of TOP_CATS) {
  const destPath = path.join(DEST_DIR, `${cat}.png`);
  
  if (aiImages[cat]) {
    // Copy AI generated image
    try {
      fs.copyFileSync(path.join(BRAIN_DIR, aiImages[cat]), destPath);
      console.log(`✅ [AI]: تم نسخ صورة القسم ${cat}`);
      successCount++;
    } catch (e) {
      console.error(`❌ فشل نسخ صورة ${cat}:`, e.message);
    }
  } else {
    // Fallback: Get first product image from scraped data
    const catProducts = scrapedProducts.filter(p => p.topCategory === cat && p.images && p.images.length > 0);
    if (catProducts.length > 0) {
      const imgWebp = catProducts[0].images[0];
      const sourceImage = path.join(__dirname, '..', 'public', imgWebp);
      const destWebp = path.join(DEST_DIR, `${cat}.webp`); // Save as webp
      try {
        if (fs.existsSync(sourceImage)) {
          fs.copyFileSync(sourceImage, destWebp);
          console.log(`✅ [Scraped]: تم نسخ صورة حقيقية للقسم ${cat}`);
          successCount++;
        }
      } catch (e) {
        console.error(`❌ فشل نسخ صورة حقيقية ${cat}:`, e.message);
      }
    } else {
      console.log(`⚠️ لا توجد صورة للقسم ${cat}`);
    }
  }
}

console.log(`\n🎉 اكتمل العمل! تم معالجة ${successCount} صورة أقسام.`);
